package it.polimi.ingsw.Networking;

public enum MessageType {
    MSG_CREATE_LOBBY,
    MSG_OK_CREATE,
    MSG_JOIN_LOBBY,
    MSG_OK_JOIN,

    MSG_ERROR_GENERIC,
    MSG_OK_GENERIC,

    MSG_INIT_LEADERCARDS_REQUEST,
    MSG_INIT_LEADERCARDS_REPLY,

    MSG_INIT_RESOURCE_REQUEST,
    MSG_INIT_RESOURCE_REPLY,
    MSG_INIT_START,

    MSG_GAME_YOUR_TURN,
    MSG_ACTION_GET_MARKET_RESOURCES,
    MSG_GAME_MARKET_RESOURCE_REQUEST,
    MSG_GAME_MARKET_RESOURCE_REPLY,
    MSG_ACTION_ACTIVATE_LEADERCARDS,
    MSG_ACTION_CHANGE_DEPOT_CONFIG,
    MSG_ACTION_BUY_DEVELOPMENT_CARD,
    MSG_GAME_BUY_DEVELOPMENT_CARD_REQUEST,
    MSG_GAME_BUY_DEVELOPMENT_CARD_REPLY,
    MSG_ACTION_ACTIVATE_PRODUCTION,
    MSG_GAME_END_TURN,

    MSG_UPDATE_MODEL,

    MSG_GAME_OVER

}
