package it.polimi.ingsw.networking.message.updateMessages.playerUpdate;

import it.polimi.ingsw.client.cli.UpdateHandler;
import it.polimi.ingsw.client.gui.UpdateHandlerGUI;
import it.polimi.ingsw.networking.message.MessageType;
import it.polimi.ingsw.networking.message.updateMessages.UpdateMessage;
import it.polimi.ingsw.server.model.enumerators.Resource;

import java.io.Serializable;

public class MSG_UPD_WarehouseDepot extends UpdateMessage implements Serializable {

    private final Resource shelf1;
    private final Resource[] shelf2;
    private final Resource[] shelf3;

    /**
     * MSG_UPD_WarehouseDepot is sent by the ClientHandler to the Client.
     * It is generated by a model.WarehouseDepot generateMessage().
     * Note: it is referred to the CurrentPlayer
     *
     * @param shelf1 The first shelf of the warehouse depot.
     * @param shelf2 The second shelf of the warehouse depot.
     * @param shelf3 The third shelf of the warehouse depot.
     */
    public MSG_UPD_WarehouseDepot(Resource shelf1, Resource[] shelf2, Resource[] shelf3) {
        super(MessageType.MSG_UPD_WarehouseDepot);

        this.shelf1 = shelf1;
        this.shelf2 = new Resource[2];
        this.shelf2[0] = shelf2[0];
        this.shelf2[1] = shelf2[1];
        this.shelf3 = new Resource[3];
        this.shelf3[0] = shelf3[0];
        this.shelf3[1] = shelf3[1];
        this.shelf3[2] = shelf3[2];
    }

    public Resource getShelf1() {
        return shelf1;
    }

    public Resource[] getShelf2() {
        return shelf2;
    }

    public Resource[] getShelf3() {
        return shelf3;
    }

    @Override
    public void executeCLI(UpdateHandler updateHandler) {
        updateHandler.updateCurrentPlayerDepot(this);
    }

    @Override
    public void executeGUI(UpdateHandlerGUI updateHandler) {
        updateHandler.updateCurrentPlayerDepot(this);
    }
}