package it.polimi.ingsw.networking.message.updateMessages.playerUpdate;

import it.polimi.ingsw.networking.message.Message;
import it.polimi.ingsw.networking.message.MessageType;
import it.polimi.ingsw.server.model.enumerators.Resource;

import java.io.Serializable;

public class MSG_UPD_Extradepot extends Message implements Serializable {

    private final Resource resource;
    private final int number;

    /**
     * MSG_UPD_Extradepot is sent by the ClientHandler to the Client
     *  It is generated by a model.LeaderCards (extradepot) generateMessage()
     * It contains the internal status of a Leader Card ExtraDepot type
     * @param resource the resource managed by the ExtraDepot
     * @param number the amount of resource placed in that ExtraDepot
     * note: it is referred to the CurrentPlayer
     * note: this message does not refer directly to the card. It is assumed that only one card with such resource exists at any given moment.
     */
    public MSG_UPD_Extradepot(Resource resource, int number) {
        super(MessageType.MSG_UPD_Extradepot);

        this.resource = resource;
        this.number = number;
    }

    public Resource getResource() {
        return this.resource;
    }

    public int getNumber() {
        return this.number;
    }
}