package it.polimi.ingsw.networking.message.updateMessages.playerUpdate;

import it.polimi.ingsw.client.cli.UpdateHandler;
import it.polimi.ingsw.networking.message.MessageType;
import it.polimi.ingsw.networking.message.updateMessages.UpdateMessage;
import it.polimi.ingsw.server.model.enumerators.Resource;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class MSG_UPD_Strongbox extends UpdateMessage implements Serializable {

    private final Map<Resource, Integer> resources;

    /**
     * MSG_UPD_Strongbox is sent by the ClientHandler to the Client.
     * It is generated by a model.Strongbox generateMessage().
     * It contains the internal status of a Strongbox.
     * Note: it is referred to the CurrentPlayer
     *
     * @param resources a map containing the resources inside the Strongbox
     */
    public MSG_UPD_Strongbox(Map<Resource, Integer> resources) {
        super(MessageType.MSG_UPD_Strongbox);

        this.resources = new HashMap<>(resources);
    }

    public Map<Resource, Integer> getResources() {
        return this.resources;
    }

    @Override
    public void executeCLI(UpdateHandler updateHandler) {
        updateHandler.updateCurrentPlayerStrongbox(this);
    }

    @Override
    public void executeGUI() {

    }
}