package it.polimi.ingsw.networking.message.updateMessages.playerUpdate;

import it.polimi.ingsw.networking.message.Message;
import it.polimi.ingsw.networking.message.MessageType;
import it.polimi.ingsw.server.model.DevelopmentCard;

import java.io.Serializable;

public class MSG_UPD_DevSlot extends Message implements Serializable {

    private final DevelopmentCard[][] cards;

    /**
     * MSG_UPD_DevSlot is sent by the ClientHandler to the Client
     *  It is generated by a model.DevelopmentSlot generateMessage()
     * It contains the internal status of a Development Slot
     * @param cards a 3x3 DevelopmentCard matrix containing the cards
     * note: it is referred to the CurrentPlayer
     */
    public MSG_UPD_DevSlot(DevelopmentCard[][] cards) {
        super(MessageType.MSG_UPD_DevSlot);

        this.cards = new DevelopmentCard[3][3];
        for (int i = 0; i < 3; i++) {
            System.arraycopy(cards[i], 0, this.cards[i], 0, 3);
        }
    }

    public DevelopmentCard[][] getCards() {
        return this.cards;
    }
}