package it.polimi.ingsw.networking.message.updateMessages.middlesUpdate;

import it.polimi.ingsw.client.cli.UpdateHandler;
import it.polimi.ingsw.networking.message.Message;
import it.polimi.ingsw.networking.message.MessageType;
import it.polimi.ingsw.networking.message.updateMessages.UpdateMessage;

import java.io.Serializable;
import java.util.Map;
import java.util.TreeMap;

public class MSG_UPD_LeaderBoard extends UpdateMessage implements Serializable {

    private final boolean enabled;
    private final Map<String, Integer> leaderboard;

    /**
     * MSG_UPD_LeaderBoard is sent by the ClientHandler to the Client.
     * It is generated by a model.middles.LeaderBoard generateMessage().
     * It contains the final leaderboard.
     * Its usage is best described in the Documentation file, Actions.
     * @param enabled Is set to True if the game is ended, False otherwise.
     * @param leaderboard The leaderboard containing the scores of the players.
     * @see it.polimi.ingsw.server.model.middles.Leaderboard;
     */
    public MSG_UPD_LeaderBoard(boolean enabled, Map<String, Integer> leaderboard) {
        super(MessageType.MSG_UPD_LeaderBoard);

        this.enabled = enabled;
        this.leaderboard = new TreeMap<>(leaderboard);
    }

    public boolean getEnabled() {
        return this.enabled;
    }

    public Map<String, Integer> getLeaderboard() {
        return this.leaderboard;
    }

    //in SOLO mode there are ALWAYS 2 keys in the Map.
    // the player, and Lorenzo. IF Lorenzo's value is 1, he's the LOSER
    //                          IF Lorenzo's value is 2, he's the WINNER

    @Override
    public void executeCLI(UpdateHandler updateHandler) {
        updateHandler.updateLeaderBoard(this);
    }

    @Override
    public void executeGUI() {

    }
}