package it.polimi.ingsw.networking.message.updateMessages;

import it.polimi.ingsw.client.cli.UpdateHandler;
import it.polimi.ingsw.client.gui.UpdateHandlerGUI;
import it.polimi.ingsw.networking.message.MessageType;

import java.io.Serializable;

public class MSG_UPD_Game extends UpdateMessage implements Serializable {

    private final int turn;
    private final int currentPlayer;
    private final int blackCrossPosition;

    /**
     * MSG_UPD_Game is sent by the ClientHandler to the Client.
     * It is generated by a model.Game generateMessage().
     * It contains the internal status of the Game.
     *
     * @param turn               The current turn of the Game.
     * @param currentPlayer      The currentPlayer, used extensively to make the control flow work.
     * @param blackCrossPosition Lorenzo's position on the FaithTrack. Used in Solo mode..
     */
    public MSG_UPD_Game(int turn, int currentPlayer, int blackCrossPosition) {
        super(MessageType.MSG_UPD_Game);

        this.turn = turn;
        this.blackCrossPosition = blackCrossPosition;
        this.currentPlayer = currentPlayer;
    }

    public int getTurn() {
        return turn;
    }

    public int getCurrentPlayer() {
        return currentPlayer;
    }

    public int getBlackCrossPosition() {
        return blackCrossPosition;
    }

    @Override
    public void executeCLI(UpdateHandler updateHandler) {
        updateHandler.updateGame(this);
    }

    @Override
    public void executeGUI(UpdateHandlerGUI updateHandler) {
        updateHandler.updateGame(this);
    }
}