package it.polimi.ingsw.networking.message.updateMessages;

import it.polimi.ingsw.networking.message.Message;
import it.polimi.ingsw.networking.message.MessageType;

import java.io.Serializable;

public class MSG_UPD_FaithTrack extends Message implements Serializable {

    private final boolean[] zones;

    /**
     * MSG_UPD_FaithTrack is sent by the ClientHandler to the Client
     *  It is generated by a model.FaithTrack generateMessage()
     * It contains the internal status of the FaithTrack, which are the zones activated
     * @param zones a 3-cell boolean array containing the values of the zones activated
     */
    public MSG_UPD_FaithTrack(boolean[] zones) {
        super(MessageType.MSG_UPD_FaithTrack);

        this.zones = new boolean[3];
        System.arraycopy(zones, 0, this.zones, 0, 3);
    }

    public boolean[] getZones() {
        return zones;
    }
}